DATA_DIR: "/media/marsdenlab/Data2/datasets/DeepLofting/files"
FILE_LIST: "/media/marsdenlab/Data2/datasets/DeepLofting/files/files.txt"

NAME:       "rf2d_mr_aorta"
TRAINER: "base"
PREDICTOR: "base"
EVALUATION: "base"
MODEL: "rf2d"
DATASET:    "axial2d"

RESULTS_DIR: "./results"
INTERVAL: 5

SPACING: 0.029
DIMS: 240
CENTER_DIMS: 200
CROP_DIMS: 128
INPUT_DIMS:
  - 16384
NUM_CHANNELS: 1
NUM_CONTOUR_POINTS: 15
CENTER: true
N_ESTIMATORS: 10
MAX_FEATURES: 25600

AUGMENT: true
AUGMENT_FACTOR: 15
AUGMENT_R_SCALE: 0.75

BALANCE_RADIUS: false
R_SMALL: 0.75
N_SAMPLE: 10000

OTHER_PATTERNS:
  - aorta

VAL_PATTERNS:
  - OSMSC0110_CLEAN

TEST_PATTERNS:
  - OSMSC0006
  - OSMSC0101
  - OSMSC0130

TRAIN_PATTERNS:
  - OSMSC0090
  - OSMSC0093
  - OSMSC0094
  - OSMSC0095
  - OSMSC0103
  - OSMSC0104
  - OSMSC0105
  - OSMSC0106
  - OSMSC0110
  - OSMSC0131
  - OSMSC0160
  - OSMSC0161
  - OSMSC0162
  - OSMSC0163
