DATA_DIR: "/media/marsdenlab/Data2/datasets/DeepLofting/files"
FILE_LIST: "/media/marsdenlab/Data2/datasets/DeepLofting/files/files.txt"

NAME:       "rf2d_ct_aorta"
TRAINER: "base"
PREDICTOR: "base"
EVALUATION: "base"
MODEL: "rf2d"
DATASET:    "axial2d"

RESULTS_DIR: "./results"
INTERVAL: 5

SPACING: 0.029
DIMS: 240
CENTER_DIMS: 200
CROP_DIMS: 128
INPUT_DIMS:
  - 16384
NUM_CHANNELS: 1
NUM_CONTOUR_POINTS: 15
CENTER: true
N_ESTIMATORS: 10
MAX_FEATURES: 16384

AUGMENT: true
AUGMENT_FACTOR: 10
AUGMENT_R_SCALE: 0.75

BALANCE_RADIUS: false
R_SMALL: 0.75
N_SAMPLE: 10000

OTHER_PATTERNS:
  - aorta

VAL_PATTERNS:
  - cabg5_CLEAN

TEST_PATTERNS:
  - OSMSC0144
  - OSMSC0148
  - OSMSC0150
  - cabg11

TRAIN_PATTERNS:
  - OSMSC0002
  - OSMSC0004
  - OSMSC0005
  - OSMSC0092
  - OSMSC0108
  - OSMSC0109
  - OSMSC0113
  - OSMSC0115
  - OSMSC0116
  - OSMSC0117
  - OSMSC0129
  - OSMSC0138
  - OSMSC0139
  - OSMSC0140
  - OSMSC0141
  - OSMSC0142
  - OSMSC0143
  - OSMSC0145
  - OSMSC0146
  - OSMSC0147
  - OSMSC0149
  - OSMSC0150
  - OSMSC0151
  - OSMSC0156
  - OSMSC0157
  - OSMSC0159
  - OSMSC0172
  - OSMSC0173
  - OSMSC0174
  - OSMSC0175
  - OSMSC0176
  - OSMSC0183
  - OSMSC0184
  - OSMSC0185
  - OSMSC0187
  - OSMSC0189
