DATA_DIR: "/media/marsdenlab/Data2/datasets/DeepLofting/files"
FILE_LIST: "/media/marsdenlab/Data2/datasets/DeepLofting/files/files.txt"

NAME:       "convnet_simple"
TRAINER: "base"
PREDICTOR: "base"
EVALUATION: "base"
MODEL: "ConvNet"
DATASET:    "axial2d"
RESULTS_DIR: "./results"
LOG_FILE: "./results/convnet_simple/log/train.txt"

MODEL_DIR: "./results/convnet_simple/model"
MODEL_NAME: "ResNetReg"
MODEL_TYPE: "ResNetReg"

LOG_STEP: 100
LEAK: 0.2
BATCH_SIZE: 4
LEARNING_RATE: 0.0001
TRAIN_STEPS: 30000
BATCH_SIZE: 4
L2_REG: 0.0
NUM_FILTERS: 32

IMAGE_TYPE: "BLUR"
BLUR_SIGMA: 3

CENTER: false
INPUT_DIMS:
  - 160
  - 160
  - 1

BALANCE_RADIUS: false
R_SMALL: 0.75
N_SAMPLE: 10000

SPACING: 0.029
DIMS: 240
CENTER_DIMS: 200
CROP_DIMS: 160
NUM_CHANNELS: 1
NUM_CONTOUR_POINTS: 15

INPUT_POOL: 4

NLAYERS: 3
CONV_DIMS: 3
NFILTERS: 32
FC_LAYERS: 0
HIDDEN_SIZE: 100
INIT: 'xavier'

VAL_PATTERNS:
  - cabg5_CLEAN

TEST_PATTERNS:
  - cabg11


TRAIN_PATTERNS:
  - cabg5_CLEAN