DATA_DIR: "/media/marsdenlab/Data2/datasets/DeepLofting/files"
FILE_LIST: "/media/marsdenlab/Data2/datasets/DeepLofting/files/files.txt"

NAME:       "gb_ct"
TRAINER: "base"
PREDICTOR: "base"
EVALUATION: "base"
MODEL: "gb"
DATASET:    "axial2d"

RESULTS_DIR: "./results"


SPACING: 0.029
DIMS: 240
CENTER_DIMS: 200
CROP_DIMS: 160
INPUT_DIMS:
  - 25600
NUM_CHANNELS: 1
NUM_CONTOUR_POINTS: 15
CENTER: false

N_ESTIMATORS: 10
MAX_FEATURES: 25600

BALANCE_RADIUS: true
R_SMALL: 0.75
N_SAMPLE: 10000

VAL_PATTERNS:
  - cabg5_CLEAN
  - OSMSC0003_CLEAN

TEST_PATTERNS:
  - OSMSC0119
  - OSMSC0144
  - OSMSC0148
  - OSMSC0150
  - OSMSC0177
  - cabg11

TRAIN_PATTERNS:
  - OSMSC0001
  - OSMSC0002
  - OSMSC0004
  - OSMSC0005
  - OSMSC0092
  - OSMSC0108
  - OSMSC0109
  - OSMSC0113
  - OSMSC0115
  - OSMSC0116
  - OSMSC0117
  - OSMSC0118
  - OSMSC0119
  - OSMSC0129
  - OSMSC0138
  - OSMSC0139
  - OSMSC0140
  - OSMSC0141
  - OSMSC0142
  - OSMSC0143
  - OSMSC0145
  - OSMSC0146
  - OSMSC0147
  - OSMSC0149
  - OSMSC0150
  - OSMSC0151
  - OSMSC0156
  - OSMSC0157
  - OSMSC0158
  - OSMSC0159
  - OSMSC0168
  - OSMSC0172
  - OSMSC0173
  - OSMSC0174
  - OSMSC0175
  - OSMSC0176
  - OSMSC0179
  - OSMSC0180
  - OSMSC0183
  - OSMSC0184
  - OSMSC0185
  - OSMSC0186
  - OSMSC0187
  - OSMSC0189
