DATA_DIR: "/media/marsdenlab/Data2/datasets/DeepLofting/files"
FILE_LIST: "/media/marsdenlab/Data2/datasets/DeepLofting/files/files_clean.txt"

NAME: "googlenet_c30_train300k_clean_mr"
TRAINER: "base"
PREDICTOR: "base"
EVALUATION: "base"
MODEL: "GoogleNet"
DATASET:    "axial2d"
RESULTS_DIR: "./results"
LOG_FILE: "./results/googlenet_c30_train300k_clean_mr/log/train.txt"

ITER_FILE: "./results/googlenet_c30_train300k_clean_mr/log/iter.txt"

MODEL_DIR: "./results/googlenet_c30_train300k_clean_mr/model"
MODEL_NAME: "googlenet"
MODEL_TYPE: "googlenet"

LOG_STEP: 2000
LEAK: 0.2
BATCH_SIZE: 4
LEARNING_RATE: 0.00005
TRAIN_STEPS: 300000
BATCH_SIZE: 4
L2_REG: 0.0
NUM_FILTERS: 32

IMAGE_TYPE: "BLUR"
BLUR_SIGMA: 3

CENTER: false
INPUT_DIMS:
  - 160
  - 160
  - 1

BALANCE_RADIUS: false
R_SMALL: 0.75
N_SAMPLE: 10000

SPACING: 0.029
DIMS: 240
CENTER_DIMS: 200
CROP_DIMS: 160
NUM_CHANNELS: 1
NUM_CONTOUR_POINTS: 30

DROPOUT: 0.6

INIT: 'xavier'

VAL_PATTERNS:
  - OSMSC0110_CLEAN
  - OSMSC0082_CLEAN

TEST_PATTERNS:
  - OSMSC0006
  - OSMSC0080
  - OSMSC0083
  - OSMSC0101
  - OSMSC0110
  - OSMSC0170
  - OSMSC0171
  - OSMSC0178

TRAIN_PATTERNS:
  - OSMSC0066
  - OSMSC0068
  - OSMSC0069
  - OSMSC0071
  - OSMSC0072
  - OSMSC0073
  - OSMSC0074
  - OSMSC0078
  - OSMSC0079
  - OSMSC0085
  - OSMSC0087
  - OSMSC0090
  - OSMSC0093
  - OSMSC0094
  - OSMSC0095
  - OSMSC0096
  - OSMSC0097
  - OSMSC0098
  - OSMSC0099
  - OSMSC0100
  - OSMSC0103
  - OSMSC0104
  - OSMSC0105
  - OSMSC0106
  - OSMSC0121
  - OSMSC0125
  - OSMSC0126
  - OSMSC0130
  - OSMSC0131
  - OSMSC0134
  - OSMSC0135
  - OSMSC0136
  - OSMSC0160
  - OSMSC0161
  - OSMSC0162
  - OSMSC0163
  - OSMSC0166
  - OSMSC0167
  - OSMSC0169
  - OSMSC0178
  - OSMSC0181
  - OSMSC0182
