DATA_DIR: "/media/marsdenlab/Data2/datasets/DeepLofting/files"
FILE_LIST: "/media/marsdenlab/Data2/datasets/DeepLofting/files/files.txt"

NAME:       "ResNetReg_2_small"
TRAINER: "base"
PREDICTOR: "base"
EVALUATION: "base"
MODEL: "ResNetReg"
DATASET:    "axial2d"
RESULTS_DIR: "./results"
LOG_FILE: "./results/ResNetReg_2_small/log/train.txt"

MODEL_DIR: "./results/ResNetReg_2_small/model"
MODEL_NAME: "ResNetReg"
MODEL_TYPE: "ResNetReg"

LOG_STEP: 100
LEAK: 0.2
BATCH_SIZE: 4
LEARNING_RATE_: 0.000001
LEARNING_RATE: 0.0001
TRAIN_STEPS: 30000
BATCH_SIZE: 4
L2_REG: 0.0
NUM_FILTERS: 32

CENTER: false
INPUT_DIMS:
  - 160
  - 160
  - 1

IMAGE_TYPE: "BLUR"
BLUR_SIGMA: 3

SIZE_SPLIT: "SMALL"

BALANCE_RADIUS: true
R_SMALL: 0.75
N_SAMPLE: 10000

SPACING: 0.029
DIMS: 240
CENTER_DIMS: 200
CROP_DIMS: 64
NUM_CHANNELS: 1
NUM_CONTOUR_POINTS: 15

NLAYERS: 4
NFILTERS_SMALL: 32
NFILTERS_LARGE: 128
FC_LAYERS: 0
HIDDEN_SIZE: 100
INIT: 'xavier'

VAL_PATTERNS:
  - OSMSC0110_CLEAN
  - cabg5_CLEAN
  - OSMSC0082_CLEAN
  - OSMSC0003_CLEAN

TEST_PATTERNS:
  - OSMSC0006
  - OSMSC0080
  - OSMSC0083
  - OSMSC0101
  - OSMSC0110
  - OSMSC0171
  - OSMSC0178
  - OSMSC0119
  - OSMSC0144
  - OSMSC0148
  - OSMSC0150
  - OSMSC0170
  - OSMSC0177
  - cabg11

TRAIN_PATTERNS:
  - OSMSC0001
  - OSMSC0002
  - OSMSC0004
  - OSMSC0005
  - OSMSC0066
  - OSMSC0068
  - OSMSC0069
  - OSMSC0071
  - OSMSC0072
  - OSMSC0073
  - OSMSC0074
  - OSMSC0078
  - OSMSC0079
  - OSMSC0085
  - OSMSC0087
  - OSMSC0090
  - OSMSC0092
  - OSMSC0093
  - OSMSC0094
  - OSMSC0095
  - OSMSC0096
  - OSMSC0097
  - OSMSC0098
  - OSMSC0099
  - OSMSC0100
  - OSMSC0103
  - OSMSC0104
  - OSMSC0105
  - OSMSC0106
  - OSMSC0108
  - OSMSC0109
  - OSMSC0113
  - OSMSC0115
  - OSMSC0116
  - OSMSC0117
  - OSMSC0118
  - OSMSC0119
  - OSMSC0121
  - OSMSC0125
  - OSMSC0126
  - OSMSC0129
  - OSMSC0130
  - OSMSC0131
  - OSMSC0134
  - OSMSC0135
  - OSMSC0136
  - OSMSC0138
  - OSMSC0139
  - OSMSC0140
  - OSMSC0141
  - OSMSC0142
  - OSMSC0143
  - OSMSC0145
  - OSMSC0146
  - OSMSC0147
  - OSMSC0149
  - OSMSC0150
  - OSMSC0151
  - OSMSC0156
  - OSMSC0157
  - OSMSC0158
  - OSMSC0159
  - OSMSC0160
  - OSMSC0161
  - OSMSC0162
  - OSMSC0163
  - OSMSC0166
  - OSMSC0167
  - OSMSC0168
  - OSMSC0169
  - OSMSC0172
  - OSMSC0173
  - OSMSC0174
  - OSMSC0175
  - OSMSC0176
  - OSMSC0178
  - OSMSC0179
  - OSMSC0180
  - OSMSC0181
  - OSMSC0182
  - OSMSC0183
  - OSMSC0184
  - OSMSC0185
  - OSMSC0186
  - OSMSC0187
  - OSMSC0189
