DATA_DIR: "/media/marsdenlab/Data2/datasets/DeepLofting/files"
FILE_LIST: "/media/marsdenlab/Data2/datasets/DeepLofting/files/files.txt"

NAME:       "rf2d_2_edge_fit_ct"
TRAINER:    "base"
PREDICTOR:  "edge_fit"
EVALUATION: "base"
MODEL:      "edge_fit"
DATASET:    "axial2d"

MODEL_YAML: "rf_2_ct.yaml"

RESULTS_DIR: "./results"

EDGE_RADIUS_RATIO: 0.3
N_STEPS: 10
INTERVAL: 5
SPACING: 0.029
DIMS: 240
CROP_DIMS: 160
NUM_CHANNELS: 1
NUM_CONTOUR_POINTS: 15

N_ESTIMATORS: 10
BALANCE_RADIUS: true
R_SMALL: 0.75
N_SAMPLE: 5000

VAL_PATTERNS:
  - cabg5_CLEAN
  - OSMSC0003_CLEAN

TEST_PATTERNS:
  - OSMSC0119
  - OSMSC0144
  - OSMSC0148
  - OSMSC0150
  - OSMSC0177
  - cabg11

TRAIN_PATTERNS:
  - OSMSC0001
  - OSMSC0002
  - OSMSC0004
  - OSMSC0005
  - OSMSC0092
  - OSMSC0108
  - OSMSC0109
  - OSMSC0113
  - OSMSC0115
  - OSMSC0116
  - OSMSC0117
  - OSMSC0118
  - OSMSC0119
  - OSMSC0129
  - OSMSC0138
  - OSMSC0139
  - OSMSC0140
  - OSMSC0141
  - OSMSC0142
  - OSMSC0143
  - OSMSC0145
  - OSMSC0146
  - OSMSC0147
  - OSMSC0149
  - OSMSC0150
  - OSMSC0151
  - OSMSC0156
  - OSMSC0157
  - OSMSC0158
  - OSMSC0159
  - OSMSC0168
  - OSMSC0172
  - OSMSC0173
  - OSMSC0174
  - OSMSC0175
  - OSMSC0176
  - OSMSC0179
  - OSMSC0180
  - OSMSC0183
  - OSMSC0184
  - OSMSC0185
  - OSMSC0186
  - OSMSC0187
  - OSMSC0189
